# Generated by Django 4.0.6 on 2022-07-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=200)),
                ('pc_id', models.SmallIntegerField(verbose_name='ID')),
                ('pc_ip', models.CharField(max_length=200)),
                ('pc_mac', models.CharField(max_length=200)),
            ],
        ),
    ]
