# Generated by Django 4.0.6 on 2022-07-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PCManager', '0002_rename_pc_ip_pc_ip_rename_pc_mac_pc_mac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='pcid',
        ),
    ]
