# Generated by Django 4.0.6 on 2022-07-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCManager', '0003_remove_pc_pcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='pcie_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pc',
            name='pcie_status',
            field=models.IntegerField(default=0),
        ),
    ]
