# Generated by Django 4.0.6 on 2022-07-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCManager', '0004_pc_pcie_power_pc_pcie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='pcie_power',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pc',
            name='pcie_status',
            field=models.IntegerField(default=100),
        ),
    ]
