# Generated by Django 4.0.6 on 2022-08-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PCManager', '0005_alter_pc_pcie_power_alter_pc_pcie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
